# frozen_string_literal: true

require 'dotenv'

Dotenv.load

AWS_ACCESS_KEY_ID = ENV['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = ENV['AWS_SECRET_ACCESS_KEY']
AWS_ACCOUNT_ID = ENV['AWS_ACCOUNT_ID']
AWS_S3_BUCKET_ARN_FOR_CHIME_RECORDING_FILE = ENV['AWS_S3_BUCKET_ARN_FOR_CHIME_RECORDING_FILE']
